In [20]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
print("Enter the entries in a single line (separated by space): ")

# User input of entries in a 
# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix = np.array(entries).reshape(R, C)
print(matrix)

Enter the number of rows:9
Enter the number of columns:9
Enter the entries in a single line (separated by space): 
0 0 0 0 9 0 3 5 4 0 3 4 0 0 6 0 0 8 0 7 0 4 0 0 1 0 6 0 0 5 1 0 0 0 8 0 4 0 0 0 5 0 0 0 9 0 6 0 0 0 4 2 0 0 7 0 3 0 0 9 0 6 0 9 0 0 6 0 0 5 7 0 1 5 6 0 8 0 0 0 0
[[0 0 0 0 9 0 3 5 4]
 [0 3 4 0 0 6 0 0 8]
 [0 7 0 4 0 0 1 0 6]
 [0 0 5 1 0 0 0 8 0]
 [4 0 0 0 5 0 0 0 9]
 [0 6 0 0 0 4 2 0 0]
 [7 0 3 0 0 9 0 6 0]
 [9 0 0 6 0 0 5 7 0]
 [1 5 6 0 8 0 0 0 0]]


In [21]:
def reset(sud):
    can = np.full((9,9), 0, list)

    for i in range(9):
        for j in range(9):
            ##print(matrix[i][j])
            if(sud[i][j] == 0):
                can[i][j] = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    return can

In [22]:
#funzioni di comodo

def stampa(m):
    for i in range(9):
        if(i!=0):
            print()
        for j in range(9):
            print(m[i][j], end=' ')
    print()
    print()

def quadrato(m, n):
    a, b = set_off(n)
    for i in range(a, a+3):
        if(i!=a):
            print()
        for j in range(b, b+3):
            print(m[i][j], end=' ')

def set_off(r):
    if(r==0):
        off_x = 0
        off_y = 0
    elif(r==1):
        off_x = 0
        off_y = 3
    elif(r==2):
        off_x = 0
        off_y = 6
    elif(r==3):
        off_x = 3
        off_y = 0
    elif(r==4):
        off_x = 3
        off_y = 3
    elif(r==5):
        off_x = 3
        off_y = 6
    elif(r==6):
        off_x = 6
        off_y = 0
    elif(r==7):
        off_x = 6
        off_y = 3
    elif(r==8):
        off_x = 6
        off_y = 6
    return off_x, off_y

In [23]:
def remove_row_value(sud, can, n, i):
    for j in range(9):
        if(sud[i][j] == 0 and n in can[i][j]):
            can[i][j].remove(n)

def check_rows(sud, can):
    for i in range(9):
        for j in range(9):
            if(sud[i][j]!=0):
                #print("Ho trovato il numero "+ str(sud[i][j]) + " e lo devo rimuovere dalle possibilità della riga " + str(i))
                remove_row_value(sud, can, sud[i][j], i)

In [24]:
def remove_col_value(sud, can, n, j):
    for i in range(9):
        if(sud[i][j] == 0 and n in can[i][j]):
            can[i][j].remove(n)
            
def check_cols(sud, can):
    for i in range(9):
        for j in range(9):
            if(sud[i][j]!=0):
                #print("Ho trovato il numero "+ str(sud[i][j]) + " e lo devo rimuovere dalle possibilità della riga " + str(j))
                remove_col_value(sud, can, sud[i][j], j)

In [25]:
def remove_sqr_value(sud, can, n, x, y):
    a = x
    b = y
    if(a >= 0 and a < 3):
        if(b >= 0 and b < 3):
            for i in range(3):
                for j in range(3):
                    if(sud[i][j] == 0):
                        if(n in can[i][j]):
                            can[i][j].remove(n)
        elif(b >= 3 and b < 6):
            for i in range(3):
                for j in range(3,6):
                    if(sud[i][j] == 0):
                        if(n in can[i][j]):
                            can[i][j].remove(n)
        elif(b >= 6 and b < 9):
            for i in range(3):
                for j in range(6,9):
                    if(sud[i][j] == 0):
                        if(n in can[i][j]):
                            can[i][j].remove(n)
    elif(a >= 3 and a < 6):
        if(b >= 0 and b < 3):
            for i in range(3,6):
                for j in range(3):
                    if(sud[i][j] == 0):
                        if(n in can[i][j]):
                            can[i][j].remove(n)
        elif(b >= 3 and b < 6):
            for i in range(3,6):
                for j in range(3,6):
                    if(sud[i][j] == 0):
                        if(n in can[i][j]):
                            can[i][j].remove(n)
        elif(b >= 6 and b < 9):
            for i in range(3,6):
                for j in range(6,9):
                    if(sud[i][j] == 0):
                        if(n in can[i][j]):
                            can[i][j].remove(n)
    elif(a >= 6 and a < 9):
        if(b >= 0 and b < 3):
            for i in range(6,9):
                for j in range(3):
                    if(sud[i][j] == 0):
                        if(n in can[i][j]):
                            can[i][j].remove(n)
        elif(b >= 3 and b < 6):
            for i in range(6,9):
                for j in range(3,6):
                    if(sud[i][j] == 0):
                        if(n in can[i][j]):
                            can[i][j].remove(n)
        elif(b >= 6 and b < 9):
            for i in range(6,9):
                for j in range(6,9):
                    if(sud[i][j] == 0):
                        if(n in can[i][j]):
                            can[i][j].remove(n)

def check_squares(sud, can):
    n = 0
    m = 0
    while (n < 9):
        for i in range(n, n+3):
            for j in range(m, m+3):
                if(sud[i][j]!=0):
                    #print("Ho trovato il numero "+ str(sud[i][j]) + " e lo devo rimuovere dalle possibilità del quadrato " + str(i) + " " + str(j))
                    remove_sqr_value(sud, can, sud[i][j], i, j)
        m = m + 3
        if (m >= 9):
            m = 0
            n = n + 3

In [26]:
def insert_naked(sud, can):
    for i in range(9):
        for j in range(9):
            if(can[i][j] != 0):
                if(len(can[i][j]) == 1):
                    sud[i][j] = can[i][j][0]
                    can[i][j] = 0
    update_candidates(sud, can)

In [27]:
def update_candidates(sud, can):
    check_rows(sud, can)
    check_cols(sud, can)
    check_squares(sud,can)

In [28]:
def hidden_rows(sud, can):
    for i in range(9):
        for j in range(9):
            if(can[i][j]!=0):
                k = 0
                while(k < len(can[i][j])):
                    count = 0
                    for l in range(9):
                        if(can[i][l]!=0):
                            if(can[i][j][k] in can[i][l] and (i,j)!=(i,l)):
                                #print(str(A[i][j][k]) + ": "+ str(A[l][m]))
                                count+=1
                    #print(count)
                    if(count==0):
                        #print(can[i][j][k], " ", (i,j))
                        sud[i][j] = can[i][j][k]
                        k = len(can[i][j])
                    k+=1
                if(sud[i][j]!=0):
                    can[i][j] = 0
    update_candidates(sud,can)

In [29]:
def hidden_cols(sud, can):
    for j in range(9):
        for i in range(9):
            if(can[i][j]!=0):
                k = 0
                while(k < len(can[i][j])):
                    count = 0
                    for l in range(9):
                        if(can[l][j]!=0):
                            if(can[i][j][k] in can[l][j] and (i,j)!=(l,j)):
                                #print(str(A[i][j][k]) + ": "+ str(A[l][m]))
                                count+=1
                    #print(count)
                    if(count==0):
                        #print(can[i][j][k], " ", (j,i))
                        sud[i][j] = can[i][j][k]
                        k = len(can[i][j])
                    k+=1
                if(sud[i][j]!=0):
                    can[i][j] = 0
    update_candidates(sud,can)

In [30]:
def hidden_squares(sud, can):
    q = 0
    w = 0
    while (q < 9):
        for i in range(q, q+3):
            for j in range(w, w+3):
                if(can[i][j]!=0):
                    k = 0
                    while(k < len(can[i][j])):
                        count = 0
                        for l in range(q, q+3):
                            for m in range(w, w+3):
                                if(can[l][m]!=0):
                                    if(can[i][j][k] in can[l][m] and (i,j)!=(l,m)):
                                        #print(str(A[i][j][k]) + ": "+ str(A[l][m]))
                                        count+=1
                        #print(count)
                        if(count==0):
                            #print(can[i][j][k], " ", (i,j))
                            sud[i][j] = can[i][j][k]
                            k = len(can[i][j])
                        k+=1
                    if(sud[i][j]!=0):
                        can[i][j] = 0
        w = w + 3
        if (w >= 9):
            w = 0
            q = q + 3
    update_candidates(sud, can)

In [31]:
def insert_hidden(sud, can):
    hidden_rows(sud, can)
    hidden_cols(sud, can)
    hidden_squares(sud, can)

In [32]:
def check_end(sud):
    for i in range(9):
        for j in range(9):
            if(sud[i][j] == 0):
                return False
    return True

In [33]:
def solve(sud):
    can = reset(sud)
    while(check_end(sud) == False):
        #stampa(sud)
        #stampa(can)
        update_candidates(sud, can)
        insert_naked(sud, can)
        insert_hidden(sud, can)
    stampa(sud)

In [34]:
solve(matrix)

6 2 1 7 9 8 3 5 4 
5 3 4 2 1 6 7 9 8 
8 7 9 4 3 5 1 2 6 
2 9 5 1 6 3 4 8 7 
4 1 7 8 5 2 6 3 9 
3 6 8 9 7 4 2 1 5 
7 4 3 5 2 9 8 6 1 
9 8 2 6 4 1 5 7 3 
1 5 6 3 8 7 9 4 2 

